version: '3'

volumes:
  esdata:
  geonetwork:
  pglog:
  nginxlog:
  apachelog:

services:
  geonetwork:
    image: geonetwork:latest
    #image: public.ecr.aws/i7c2f1z3/scotgov-custom-geonetwork:latest
    #image: scotgov-custom-geonetwork:latest
    restart: unless-stopped
    container_name: geonetwork
    ports:
      - 8080:8080
    user: 0:0
    environment:
      DATA_DIR: /catalogue-data
      JAVA_OPTS: 
        -Dorg.eclipse.jetty.annotations.AnnotationParser.LEVEL=OFF
        -Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true
        -Xms512M -Xss512M -Xmx2G -XX:+UseConcMarkSweepGC
        -Dgeonetwork.resources.dir=/var/lib/jetty/webapps/geonetwork/WEB-INF/data/data/resources
        -Dgeonetwork.data.dir=/var/lib/jetty/webapps/geonetwork/WEB-INF/data
        -Dgeonetwork.codeList.dir=/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/codelist
        -Dgeonetwork.schema.dir=/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins
      ES_HOST: ${ES_HOST}
      ES_PROTOCOL: ${ES_PROTOCOL}
      ES_PORT: ${ES_PORT}
      ES_URL: ${ES_URL}
      KB_URL: ${KB_URL}
      GEONETWORK_DB_TYPE: postgres
      GEONETWORK_DB_HOST: ${POSTGRES_DB_HOST}
      GEONETWORK_DB_PORT: ${POSTGRES_DB_PORT}
      GEONETWORK_DB_NAME: ${POSTGRES_DB_NAME}
      GEONETWORK_DB_USERNAME: ${POSTGRES_DB_USERNAME}
      GEONETWORK_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
      GEONETWORK_MICROSERVICESPROXY_TARGETURI: http://ogc-api-records-service:8080
  
    volumes:
      # general overrides
      - geonetwork:/catalogue-data
      - ./thesauri/external/thesauri/theme:/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/codelist/external/thesauri/theme
      - ./geonetwork/catalog/locales/en-admin.json:/var/lib/jetty/webapps/geonetwork/catalog/locales/en-admin.json
      - ./geonetwork/catalog/locales/en-core.json:/var/lib/jetty/webapps/geonetwork/catalog/locales/en-core.json
      - ./geonetwork/catalog/locales/en-editor.json:/var/lib/jetty/webapps/geonetwork/catalog/locales/en-editor.json
      # dashboards
      - ./geonetwork/catalog/js/admin/DashboardController.js:/var/lib/jetty/webapps/geonetwork/catalog/js/admin/DashboardController.js
      # datepicker layout fix
      - ./geonetwork/catalog/components/edit/datepicker/partials/datepicker.html:/var/lib/jetty/webapps/geonetwork/catalog/components/edit/datepicker/partials/datepicker.html
      - ./geonetwork/catalog/views/default/less/gn_editor_default.less:/var/lib/jetty/webapps/geonetwork/catalog/views/default/less/gn_editor_default.less
      # data quality snippets
      - ../geonetwork-snippets/gemini23-index-fields/index-subtemplate.xsl:/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139.gemini23/index-fields/index-subtemplate.xsl
      - ../geonetwork-snippets/iso19139-index-fields/index-subtemplate.xsl:/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139/index-fields/index-subtemplate.xsl  
      # group logo
      - ./geonetwork/catalog/views/default/less/gn_search_default.less:/var/lib/jetty/webapps/geonetwork/catalog/views/default/less/gn_search_default.less
      - ./geonetwork/catalog/components/utility/UtilityDirective.js:/var/lib/jetty/webapps/geonetwork/catalog/components/utility/UtilityDirective.js
      - ./geonetwork/catalog/components/utility/partials/recordOriginLogo.html:/var/lib/jetty/webapps/geonetwork/catalog/components/utility/partials/recordOriginLogo.html
      - ./geonetwork/catalog/views/default/templates/recordView/metadata.html:/var/lib/jetty/webapps/geonetwork/catalog/views/default/templates/recordView/metadata.html
      - ./geonetwork/catalog/style/gn_metadata.less:/var/lib/jetty/webapps/geonetwork/catalog/style/gn_metadata.less
      - ./geonetwork/catalog/locales/en-search.json:/var/lib/jetty/webapps/geonetwork/catalog/locales/en-search.json
      # schema overrides
      # gemini 2.3
      - ../iso19139.gemini23/src/main/plugin/iso19139.gemini23:/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139.gemini23
      - ../iso19139.gemini23/src/main/config/translations/en-schema-iso19139.gemini23.json:/var/lib/jetty/webapps/geonetwork/catalog/locales/en-schema-iso19139.gemini23.json
      - ../iso19139.gemini23/target/schema-iso19139.gemini23-4.2.2-SNAPSHOT.jar:/var/lib/jetty/webapps/geonetwork/WEB-INF/lib/gn-schema-iso19139.gemini23-4.2.2-SNAPSHOT.jar
      # gemini 2.2
      - ../iso19139.gemini22/src/main/plugin/iso19139.gemini22:/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139.gemini22
      - ../iso19139.gemini22/src/main/config/translations/en-schema-iso19139.gemini22.json:/var/lib/jetty/webapps/geonetwork/catalog/locales/en-schema-iso19139.gemini22.json
      - ../iso19139.gemini22/target/schema-iso19139.gemini22-4.2.2-SNAPSHOT.jar:/var/lib/jetty/webapps/geonetwork/WEB-INF/lib/gn-schema-iso19139.gemini22-4.2.2-SNAPSHOT.jar
      - ../iso19139.gemini22/src/main/plugin/iso19139.gemini22/process/xml_gemini22gemini23-schemaupgrade.xsl:/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139/process/xml_gemini22gemini23-schemaupgrade.xsl
      # iso19139
      - ./geonetwork/WEB-INF/data/config/schema_plugins/iso19139/index-fields/default.xsl:/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139/index-fields/default.xsl
      - ./geonetwork/WEB-INF/data/config/schema_plugins/iso19139/layout/tpl-rdf.xsl:/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139/layout/tpl-rdf.xsl
      - ./geonetwork/WEB-INF/data/config/schema_plugins/iso19139/loc/eng/labels.xml:/var/lib/jetty/webapps/geonetwork/WEB-INF/data/config/schema_plugins/iso19139/loc/eng/labels.xml
    networks:
      - esnet

  datahub:
    image: geonetwork/geonetwork-ui-datahub:master
    container_name: datahub
    ports:
      - 8081:80
    environment:
      GN4_API_URL: ${GN_PROTOCOL}://${DH_HOST}:${DH_PORT}/geonetwork/srv/api
    restart: unless-stopped
    volumes:
      #- ./datahub/assets:/assets
      - ./datahub/conf/:/conf
    networks:
    - esnet

  ogc-api-records-service:
    image: geonetwork/gn-cloud-ogc-api-records-service:4.2.3-0
    environment:
      SPRING_PROFILES_ACTIVE: standalone
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_DB_HOST}:${POSTGRES_DB_PORT}/${POSTGRES_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_DB_PASSWORD}
      GN_BASEURL: ${GN_PROTOCOL}://${GN_URL}/geonetwork/api
      GN_LEGACY_URL: ${GN_PROTOCOL}://${GN_URL}/geonetwork
      GN_INDEX_URL: ${ES_URL}
      SERVER_FORWARDHEADERSSTRATEGY: FRAMEWORK

    restart: unless-stopped
    container_name: ogc-api-service

    networks:
      - esnet

  nginx:
    image: nginx
    container_name: nginx
    volumes:
          - ./nginx/default.local:/etc/nginx/conf.d/default.conf
          - ./nginx/servers:/etc/nginx/servers
          - ./nginx/locations:/etc/nginx/locations
          - ./nginx/root/robots.txt:/var/www/html/robots.txt
          - nginxlog:/var/log/nginx
    ports:
      - "80:80"
      - "8443:8443"
    security_opt:
      - no-new-privileges=true
    logging:
          driver: "json-file"
    networks:
      - esnet
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/robots.txt || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 5
    restart: unless-stopped

networks:
  esnet:
    driver: bridge