version: '3'

volumes:
  esdata:

services:
  elasticsearch:
      image: elasticsearch:7.16.3
      # build:
      #   context: ./elasticsearch
      container_name: elasticsearch
      restart: unless-stopped
      logging:
        driver: "json-file"
      networks:
        - esnet
      ports:
        - "9200:9200"
      security_opt:
        - no-new-privileges=true
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65535
          hard: 65535
      environment:
        - "ES_JAVA_OPTS=-Xms1G -Xmx1G" 
        - discovery.type=single-node
      volumes:
        - esdata:/usr/share/elasticsearch/data
      healthcheck:
        test: ["CMD-SHELL", "curl -i -H \"Accept: application/json\" -f http://localhost:9200/gn-records || exit 1"]
        interval: 3m
        timeout: 10s
        retries: 3

  kibana:
    image: kibana:7.16.3
    #image: amazon/opendistro-for-elasticsearch-kibana:1.9.0
    container_name: kibana
    restart: unless-stopped
    environment:
      ELASTICSEARCH_URL: ${ES_URL}
      ES_USERNAME: ${ES_USERNAME}
      ES_PASSWORD: ${ES_PASSWORD}
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: 'true'
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    logging:
          driver: "json-file"
    ports:
      - "5601:5601"
    security_opt:
      - no-new-privileges=true
    networks:
      - esnet
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:5601/login || exit 1"]
        interval: 1m
        timeout: 10s
        retries: 5

networks:
  esnet:
    driver: bridge