version: '3.1'


services:
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.11.1
    container_name: metricbeat
    command: metricbeat -e -strict.perms=false
    restart: unless-stopped
    environment:
      - METRIC_HOST=${METRIC_HOST}
      - NGINX_HOST=${NGINX_HOST}
      - ES_HOST=${ES_HOST}
      - ES_PORT=${ES_PORT}
      - METRIC_GN_USER=${METRIC_GN_USER}
      - METRIC_GN_PASSWORD=${METRIC_GN_PASSWORD}
    volumes:
      - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - ./metricbeat/modules.d:/usr/share/metricbeat/modules.d
      - ./metricbeat/templates:/usr/share/metricbeat/templates/7/dashboard
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - esnet


  filebeat:
    image: docker.elastic.co/beats/filebeat:7.11.1
    container_name: filebeat
    command: filebeat -e -strict.perms=false
    restart: unless-stopped
    environment:
      - METRIC_HOST=${METRIC_HOST}
      - NGINX_HOST=${NGINX_HOST}
      - ES_HOST=${ES_HOST}
      - ES_PORT=${ES_PORT}
      - METRIC_GN_USER=${METRIC_GN_USER}
      - METRIC_GN_PASSWORD=${METRIC_GN_PASSWORD}
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/modules.d:/usr/share/filebeat/modules.d
      - ./filebeat/templates:/usr/share/filebeat/kibana/7/dashboard
      - pglog:/usr/share/filebeat/analyzedlogs/postgresql:ro
      - nginxlog:/usr/share/filebeat/analyzedlogs/nginx:ro
      - apachelog:/usr/share/filebeat/analyzedlogs/apache:ro
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - esnet
      